### ISSUE TITLE
Tool idea xmlstarlet to convert between metadata standards

### ISSUE THREAD

**Issue by yvanlebras** [galaxyecology/tools-ecology#51]
Need to add xmlstarlet conda recipies + create a Galaxy tool who can for example apply such a "basic" command line:

`xmlstarlet tr standardx2standardy.xsl input_standardx.xml > output_standardy.xml`

where `standardx2standardy.xsl` is the xsl file defining mapping between both metadata XML schemas, `input_standardx.xml` the metadata input file using standard "x", `output_standardy.xml` the metadata output file using standard "y".

I am using it for example to convert ISO19139 metadata based xml file into EML (Ecological Metadata Language) metadata based xml file, like described here https://github.com/NCEAS/iso2eml

**Comment by yvanlebras** [comment]
And I think this can be of interest for Elixir Implementation Study 2021, "Strengthen Data Management in Galaxy", no ? Maybe we can also provide a "list" of "well known" xsl / metadata standard ?

Unfortunately, it seems xmlstarlet is not in conda...

**Comment by bgruening** [comment]
We can help with the conda-forge package ...

**Comment by yvanlebras** [comment]
Could be amazing! And if interest for other use I guess!

**Comment by bgruening** [comment]
here you go: https://github.com/conda-forge/staged-recipes/pull/16458

**Comment by yvanlebras** [comment]
done!
